---
- name: server.yml anpassen
  template:
    src: server.xml.j2
    dest: "{{ jira_install_path }}/conf/server.xml"
    owner: "{{ jira_user }}"
    group: "{{ jira_group }}"
    mode: '0644'
  notify: Jira neustarten

- name: setenv.sh anpassen 
  template:
    src: setenv.sh.j2
    dest: "{{ jira_install_path }}/bin/setenv.sh"
    owner: "{{ jira_user }}"
    group: "{{ jira_group }}"
    mode: '0755'
  notify: Jira neustarten