---
- name: Sicherstellen, das die Berechtigung der Jira-Verzeichnisse richtig gesetzt ist 
  file:
    path: "{{ jira_install_path }}"
    state: directory
    recurse: yes
    owner: "{{ jira_user }}"
    group: "{{ jira_group }}"
