---
- name: Erstellen von Systemd-Service
  template:
    src: jira.service.j2
    dest: /etc/systemd/system/jira.service
    mode: '0644'

- name: Systemd reloaden 
  systemd:
    daemon_reload: yes

- name: Aktivieren & Starten von Jira service
  systemd:
    name: jira
    enabled: yes
    state: started
